import { useEffect, useState, type FormEvent } from 'react';
import { motion, useReducedMotion, useScroll, useSpring, useTransform } from 'motion/react';
import { ArrowRight, BriefcaseBusiness, Calculator, Check, ChevronDown, ChevronRight, ClipboardList, Compass, FileCheck2, HeartHandshake, House, MapPinned, Menu, Route, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react';
import brandMark from '../../app/assets/brand/mudavi_mark_light.svg';

type Locale = 'es' | 'pt' | 'en';
const languages: { code: Locale; flag: string; label: string }[] = [
  { code: 'es', flag: '🇦🇷', label: 'Español' }, { code: 'pt', flag: '🇧🇷', label: 'Português' }, { code: 'en', flag: '🇺🇸', label: 'English' },
];

const copy = {
  es: {
    nav: ['Cómo funciona', 'Por qué Mudavi', 'Confianza', 'Quiero conocer Mudavi'], menu: ['Abrir menú', 'Cerrar menú', 'Seleccionar idioma'],
    hero: ['Para quienes están pensando en vivir en Brasil', 'Mudarte de país ya es difícil.', 'Entender el camino no debería serlo.', 'Mudavi es una guía digital gratuita que te ayuda a ordenar las decisiones, los preparativos y los próximos pasos de tu mudanza a Brasil según tu realidad.', 'Quiero probar Mudavi', 'Entender cómo puede ayudarme', 'Gratis para usar. No es una consultoría ni vende asesoramiento.'],
    phone: ['Vista previa de la herramienta Mudavi', 'TU PRÓXIMO PASO', 'Tu plan para vivir en Brasil', 'Preparación', 'AHORA', 'Reuní tu documentación', '3 de 5 tareas completadas', 'DESPUÉS', 'Confirmá tu ciudad', 'Florianópolis y 2 alternativas', 'Orientación revisada y fuentes visibles'],
    problem: ['MENOS RUIDO. MÁS DIRECCIÓN.', 'No necesitás cien pestañas abiertas.', 'Necesitás saber qué hacer ahora.', 'Mudavi conecta lo que hoy aparece separado: ciudad, documentos, dinero, trabajo, vivienda y llegada.'],
    benefits: [['Elegí con contexto', 'Compará ciudades según tu realidad, tus prioridades y lo que no estás dispuesto a negociar.'], ['Seguí un orden posible', 'Convertí trámites, vivienda, trabajo y costos en próximos pasos claros, sin empezar todo a la vez.'], ['Avanzá con respaldo', 'Entendé de dónde sale cada orientación y verificá la información importante en fuentes oficiales.']],
    journey: ['UN PLAN QUE SE ADAPTA', 'Tu mudanza no es igual a la de nadie.', 'Vas solo, con familia o con tu mascota. Trabajás remoto o buscás nuevas oportunidades. Ya elegiste ciudad o todavía estás comparando. Mudavi empieza por tu contexto.'],
    bullets: ['Recomendaciones según tus prioridades reales', 'Tareas ordenadas por dependencia y momento', 'Progreso guardado para continuar cuando puedas'],
    steps: [['HOY', 'Definí tu perfil', '4 minutos'], ['PRÓXIMO', 'Compará tus ciudades', 'Con criterios que importan para vos'], ['TU PLAN', 'Avanzá paso a paso', 'Sin perder lo que ya resolviste']],
    trust: ['UNA GUÍA, NO UNA CONSULTORÍA', 'Información para avanzar con más claridad.', 'Mudavi es una herramienta gratuita. Organiza información pública y tu contexto para ayudarte a planificar, sin cobrar por el acceso ni vender asesoramiento individual.', 'Fuentes a la vista', 'Sabés qué información consultar y dónde verificarla.', 'Vos tomás las decisiones', 'Mudavi no reemplaza asesoramiento jurídico, migratorio, médico o financiero.'],
    audience: ['¿Estás pensando en mudarte en los próximos meses?', '¿Todavía comparás ciudades?', '¿No sabés qué resolver primero?'],
    features: ['TODO LO QUE IMPORTA, EN UN MISMO RECORRIDO', 'De la primera duda a tu llegada.', 'Mudavi no es otra colección de artículos. Usa tu contexto para conectar decisiones que dependen unas de otras.', ['Ciudades y recomendación', 'Compará opciones y entendé qué ciudad se acerca más a tus prioridades y restricciones.'], ['Plan personalizado', 'Recibí una secuencia práctica que cambia según tu familia, plazo, ingresos y necesidades.'], ['Documentos y regularización', 'Organizá requisitos, dependencias y fuentes oficiales para saber qué preparar y verificar.'], ['Costos y escenarios', 'Explorá estimaciones de instalación, 30 y 90 días con las hipótesis claramente visibles.'], ['Trabajo y vivienda', 'Identificá obstáculos reales de ingresos, idioma, garantías, alquiler y acceso a oportunidades.'], ['Llegada y vida práctica', 'Continuá con tareas para la primera semana, el primer mes y los pasos de adaptación.']],
    founder: ['NACIDA ENTRE DOS PAÍSES', 'Una herramienta creada desde una experiencia real.', 'Soy Pablo Costa, brasileño, desarrollador y vivo en Argentina. Conozco de cerca las dudas que aparecen cuando una vida necesita cruzar fronteras.', 'Creé Mudavi para transformar información dispersa en una orientación práctica para quien está evaluando el camino inverso: de Argentina a Brasil.', 'Mudavi combina tecnología, contexto local y fuentes verificables. La herramienta no pretende decidir por nadie; busca que cada persona pueda decidir mejor.'],
    signup: ['PRIMERAS PRUEBAS', '¿Querés conocer Mudavi por dentro?', 'Estamos preparando las primeras pruebas con personas que planean una mudanza real. Participar y usar Mudavi es gratis.', 'Tu email', 'tu@email.com', 'Quiero participar', 'Listo. Te avisaremos cuando empiecen las primeras pruebas.', 'Sin pagos ni spam. Solo noticias importantes sobre Mudavi.'], footer: 'De la incertidumbre al próximo paso.',
  },
  pt: {
    nav: ['Como funciona', 'Por que Mudavi', 'Confiança', 'Quero conhecer o Mudavi'], menu: ['Abrir menu', 'Fechar menu', 'Selecionar idioma'],
    hero: ['Para quem está pensando em viver no Brasil', 'Mudar de país já é difícil.', 'Entender o caminho não precisa ser.', 'O Mudavi é um guia digital gratuito que ajuda você a organizar as decisões, os preparativos e os próximos passos da mudança para o Brasil de acordo com a sua realidade.', 'Quero testar o Mudavi', 'Entender como ele pode me ajudar', 'Grátis para usar. Não é consultoria e não vende assessoria.'],
    phone: ['Prévia da ferramenta Mudavi', 'SEU PRÓXIMO PASSO', 'Seu plano para viver no Brasil', 'Preparação', 'AGORA', 'Reúna sua documentação', '3 de 5 tarefas concluídas', 'DEPOIS', 'Confirme sua cidade', 'Florianópolis e 2 alternativas', 'Orientação revisada e fontes visíveis'],
    problem: ['MENOS RUÍDO. MAIS DIREÇÃO.', 'Você não precisa de cem abas abertas.', 'Precisa saber o que fazer agora.', 'O Mudavi conecta o que hoje aparece separado: cidade, documentos, dinheiro, trabalho, moradia e chegada.'],
    benefits: [['Escolha com contexto', 'Compare cidades de acordo com a sua realidade, suas prioridades e o que você não abre mão.'], ['Siga uma ordem possível', 'Transforme documentos, moradia, trabalho e custos em próximos passos claros, sem começar tudo ao mesmo tempo.'], ['Avance com respaldo', 'Entenda de onde vem cada orientação e verifique as informações importantes em fontes oficiais.']],
    journey: ['UM PLANO QUE SE ADAPTA', 'Sua mudança não é igual à de ninguém.', 'Você vai sozinho, com a família ou com seu pet. Trabalha remotamente ou busca novas oportunidades. Já escolheu a cidade ou ainda está comparando. O Mudavi começa pelo seu contexto.'],
    bullets: ['Recomendações de acordo com suas prioridades reais', 'Tarefas ordenadas por dependência e momento', 'Progresso salvo para continuar quando puder'],
    steps: [['HOJE', 'Defina seu perfil', '4 minutos'], ['PRÓXIMO', 'Compare suas cidades', 'Com critérios importantes para você'], ['SEU PLANO', 'Avance passo a passo', 'Sem perder o que já resolveu']],
    trust: ['UM GUIA, NÃO UMA CONSULTORIA', 'Informação para você avançar com mais clareza.', 'O Mudavi é uma ferramenta gratuita. Ele organiza informações públicas e o seu contexto para ajudar no planejamento, sem cobrar pelo acesso nem vender atendimento individual.', 'Fontes à vista', 'Saiba quais informações consultar e onde verificá-las.', 'Você toma as decisões', 'O Mudavi não substitui assessoria jurídica, migratória, médica ou financeira.'],
    audience: ['Pensando em se mudar nos próximos meses?', 'Ainda comparando cidades?', 'Sem saber o que resolver primeiro?'],
    features: ['TUDO O QUE IMPORTA, EM UMA ÚNICA JORNADA', 'Da primeira dúvida até a sua chegada.', 'O Mudavi não é apenas mais uma coleção de artigos. Ele usa o seu contexto para conectar decisões que dependem umas das outras.', ['Cidades e recomendação', 'Compare opções e entenda qual cidade mais se aproxima das suas prioridades e restrições.'], ['Plano personalizado', 'Receba uma sequência prática que muda de acordo com sua família, prazo, renda e necessidades.'], ['Documentos e regularização', 'Organize requisitos, dependências e fontes oficiais para saber o que preparar e verificar.'], ['Custos e cenários', 'Explore estimativas de instalação, 30 e 90 dias com as premissas claramente visíveis.'], ['Trabalho e moradia', 'Identifique obstáculos reais de renda, idioma, garantias, aluguel e acesso a oportunidades.'], ['Chegada e vida prática', 'Continue com tarefas para a primeira semana, o primeiro mês e os passos de adaptação.']],
    founder: ['NASCIDO ENTRE DOIS PAÍSES', 'Um guia criado a partir de uma experiência real.', 'Sou Pablo Costa, brasileiro, desenvolvedor e vivo na Argentina. Conheço de perto as dúvidas que surgem quando uma vida precisa atravessar fronteiras.', 'Criei o Mudavi para transformar informação dispersa em orientação prática para quem está avaliando o caminho inverso: da Argentina para o Brasil.', 'O Mudavi combina tecnologia, contexto local e fontes verificáveis. Ele não pretende decidir por ninguém; ajuda cada pessoa a decidir melhor.'],
    signup: ['PRIMEIROS TESTES', 'Quer conhecer o Mudavi por dentro?', 'Estamos preparando os primeiros testes com pessoas que planejam uma mudança real. Participar e usar o Mudavi é grátis.', 'Seu email', 'seu@email.com', 'Quero participar', 'Tudo certo. Avisaremos quando os primeiros testes começarem.', 'Sem pagamentos e sem spam. Apenas notícias importantes sobre o Mudavi.'], footer: 'Da incerteza ao próximo passo.',
  },
  en: {
    nav: ['How it works', 'Why Mudavi', 'Trust', 'Discover Mudavi'], menu: ['Open menu', 'Close menu', 'Select language'],
    hero: ['For people thinking about living in Brazil', 'Moving countries is already hard.', 'Finding your way forward should not be.', 'Mudavi is a free digital guide that helps you organize the decisions, preparation, and next steps of moving to Brazil around your real life.', 'I want to try Mudavi', 'See how it can help me', 'Free to use. It is not a consultancy and does not sell advice.'],
    phone: ['Preview of the Mudavi tool', 'YOUR NEXT STEP', 'Your plan for living in Brazil', 'Preparation', 'NOW', 'Gather your documents', '3 of 5 tasks completed', 'NEXT', 'Confirm your city', 'Florianópolis and 2 alternatives', 'Reviewed guidance and visible sources'],
    problem: ['LESS NOISE. MORE DIRECTION.', 'You do not need a hundred open tabs.', 'You need to know what to do next.', 'Mudavi connects what is scattered today: cities, documents, money, work, housing, and arrival.'],
    benefits: [['Choose with context', 'Compare cities based on your reality, your priorities, and what you are not willing to compromise.'], ['Follow a realistic order', 'Turn paperwork, housing, work, and costs into clear next steps without starting everything at once.'], ['Move forward with support', 'Understand where each recommendation comes from and verify important information through official sources.']],
    journey: ['A PLAN THAT ADAPTS', 'Your move is unlike anyone else’s.', 'You may be moving alone, with family, or with a pet. You may work remotely or be looking for new opportunities. You may have chosen a city or still be comparing. Mudavi starts with your context.'],
    bullets: ['Recommendations based on your real priorities', 'Tasks ordered by timing and dependencies', 'Saved progress so you can continue when ready'],
    steps: [['TODAY', 'Define your profile', '4 minutes'], ['NEXT', 'Compare your cities', 'Using criteria that matter to you'], ['YOUR PLAN', 'Move forward step by step', 'Without losing what you have completed']],
    trust: ['A GUIDE, NOT A CONSULTANCY', 'Information to help you move forward with clarity.', 'Mudavi is a free tool. It organizes public information and your context to support your planning, without charging for access or selling individual advice.', 'Sources in view', 'Know what information to consult and where to verify it.', 'You make the decisions', 'Mudavi does not replace legal, immigration, medical, or financial advice.'],
    audience: ['Planning to move in the next few months?', 'Still comparing cities?', 'Unsure what to solve first?'],
    features: ['EVERYTHING THAT MATTERS, IN ONE JOURNEY', 'From your first question to your arrival.', 'Mudavi is not another collection of articles. It uses your context to connect decisions that depend on one another.', ['Cities and recommendations', 'Compare options and understand which city better fits your priorities and constraints.'], ['A personalized plan', 'Get a practical sequence shaped by your family, timeline, income, and needs.'], ['Documents and residency', 'Organize requirements, dependencies, and official sources so you know what to prepare and verify.'], ['Costs and scenarios', 'Explore moving, 30-day, and 90-day estimates with their assumptions clearly visible.'], ['Work and housing', 'Identify real obstacles involving income, language, guarantees, rent, and access to opportunities.'], ['Arrival and daily life', 'Keep going with tasks for your first week, first month, and the steps toward settling in.']],
    founder: ['BORN BETWEEN TWO COUNTRIES', 'A tool created from real experience.', 'I’m Pablo Costa, a Brazilian developer living in Argentina. I know firsthand the questions that emerge when your life has to cross borders.', 'I created Mudavi to turn scattered information into practical guidance for people considering the journey in the other direction: from Argentina to Brazil.', 'Mudavi combines technology, local context, and verifiable sources. It is not meant to decide for anyone; it helps each person make a better-informed decision.'],
    signup: ['FIRST TESTS', 'Want to see Mudavi from the inside?', 'We are preparing the first tests with people planning a real move. Joining and using Mudavi is free.', 'Your email', 'you@email.com', 'I want to take part', 'You are on the list. We will let you know when the first tests begin.', 'No payments and no spam. Only important Mudavi updates.'], footer: 'From uncertainty to your next step.',
  },
} as const;

const benefitIcons = [Compass, Route, FileCheck2];
const featureIcons = [MapPinned, ClipboardList, FileCheck2, Calculator, BriefcaseBusiness, House];
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } };
function Logo() { return <a className="logo" href="#inicio" aria-label="Mudavi"><span className="logo-mark"><img src={brandMark} alt="" /></span><span>Mudavi</span></a>; }

function LanguageSelector({ locale, onChange, label }: { locale: Locale; onChange: (value: Locale) => void; label: string }) {
  const [open, setOpen] = useState(false); const current = languages.find((item) => item.code === locale)!;
  return <div className="language-selector"><button className="language-trigger" type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={label}><span aria-hidden="true">{current.flag}</span><span>{current.code.toUpperCase()}</span><ChevronDown size={14} /></button>{open && <div className="language-menu" role="menu">{languages.map((item) => <button type="button" role="menuitem" className={item.code === locale ? 'active' : ''} key={item.code} onClick={() => { onChange(item.code); setOpen(false); }}><span aria-hidden="true">{item.flag}</span><span>{item.label}</span>{item.code === locale && <Check size={15} />}</button>)}</div>}</div>;
}

function PhonePreview({ text }: { text: readonly string[] }) { return <div className="phone-wrap" aria-label={text[0]}><div className="phone-shadow" /><div className="phone"><span className="dynamic-island" aria-hidden="true" /><img className="phone-screen" src="/mudavi-app-iphone17.png" alt={text[0]} /></div></div>; }

export function App() {
  const [locale, setLocale] = useState<Locale>(() => navigator.language.toLowerCase().startsWith('pt') ? 'pt' : navigator.language.toLowerCase().startsWith('en') ? 'en' : 'es');
  const [menuOpen, setMenuOpen] = useState(false); const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const reduceMotion = useReducedMotion(); const t = copy[locale];
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 120, damping: 28, mass: .25 });
  const phoneY = useTransform(scrollYProgress, [0, .22], [0, reduceMotion ? 0 : 90]);
  useEffect(() => { document.documentElement.lang = locale; document.title = `Mudavi | ${t.hero[1]} ${t.hero[2]}`; }, [locale, t.hero]);
  const changeLocale = (value: Locale) => { setLocale(value); setSent(false); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (email) setSent(true); };
  return <div className="site-shell"><motion.div className="reading-progress" style={{ scaleX: progress }} /><header className="nav-shell"><nav className="nav" aria-label="Mudavi"><Logo /><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#como-funciona" onClick={() => setMenuOpen(false)}>{t.nav[0]}</a><a href="#diferencial" onClick={() => setMenuOpen(false)}>{t.nav[1]}</a><a href="#confianza" onClick={() => setMenuOpen(false)}>{t.nav[2]}</a><a className="nav-cta" href="#acceso" onClick={() => setMenuOpen(false)}>{t.nav[3]}</a></div><div className="nav-tools"><LanguageSelector locale={locale} onChange={changeLocale} label={t.menu[2]} /><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={menuOpen ? t.menu[1] : t.menu[0]}>{menuOpen ? <X /> : <Menu />}</button></div></nav></header><main>
    <section className="hero" id="inicio"><div className="hero-light" /><div className="hero-inner"><motion.div className="hero-copy" initial="hidden" animate="visible" variants={reveal} transition={{ duration: reduceMotion ? 0 : .7 }}><div className="eyebrow"><span>01</span>{t.hero[0]}</div><h1>{t.hero[1]}<br /><span>{t.hero[2]}</span></h1><p className="hero-lead">{t.hero[3]}</p><div className="hero-actions"><a className="button button-primary" href="#acceso">{t.hero[4]}<ArrowRight size={18} /></a><a className="text-link" href="#como-funciona">{t.hero[5]}<ChevronRight size={17} /></a></div><div className="trust-line"><ShieldCheck size={18} /><span>{t.hero[6]}</span></div></motion.div><motion.div className="hero-product" style={{ y: phoneY }} initial={{ opacity: 0, scale: .9, rotate: 3 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: reduceMotion ? 0 : 1.1, delay: .15, ease: [.22, 1, .36, 1] }}><span className="product-caption">MUDAVI / PRODUCT 01</span><PhonePreview text={t.phone} /></motion.div></div><a className="scroll-cue" href="#como-funciona" aria-label={t.nav[0]}><span /></a></section>
    <section className="audience-strip" aria-label={t.problem[0]}>{t.audience.map((item, index) => <div key={item}><span>0{index + 1}</span><p>{item}</p></div>)}</section>
    <section className="problem band" id="como-funciona"><motion.div className="section-intro" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .4 }} variants={reveal}><p className="section-label">{t.problem[0]}</p><h2>{t.problem[1]}<br />{t.problem[2]}</h2><p>{t.problem[3]}</p></motion.div><div className="benefit-grid">{t.benefits.map(([title, text], index) => { const Icon = benefitIcons[index]; return <motion.article className="benefit" key={title} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .35 }} variants={reveal} transition={{ delay: reduceMotion ? 0 : index * .1 }}><span className="benefit-icon"><Icon /></span><span className="benefit-number">0{index + 1}</span><h3>{title}</h3><p>{text}</p></motion.article>; })}</div></section>
    <section className="journey band" id="diferencial"><div className="journey-copy"><p className="section-label">{t.journey[0]}</p><h2>{t.journey[1]}</h2><p>{t.journey[2]}</p><ul>{t.bullets.map((item) => <li key={item}><Check size={17} />{item}</li>)}</ul></div><div className="journey-visual" aria-label={t.journey[1]}><div className="route-line" />{t.steps.map(([label, title, text], index) => <div className={`route-step ${index === 0 ? 'active' : ''}`} key={title}><span>{index + 1}</span><div><small>{label}</small><strong>{title}</strong><p>{text}</p></div></div>)}</div></section>
    <section className="features band" id="recursos"><div className="features-heading"><div><p className="section-label">{t.features[0]}</p><h2>{t.features[1]}</h2></div><p>{t.features[2]}</p></div><div className="feature-grid">{t.features.slice(3).map((feature, index) => { const [title, text] = feature; const Icon = featureIcons[index]; return <article className="feature-item" key={title}><span><Icon size={21} /></span><h3>{title}</h3><p>{text}</p></article>; })}</div></section>
    <section className="founder band"><div className="founder-profile"><span className="founder-avatar"><UserRound size={34} /></span><div><strong>Pablo Costa</strong><small>Founder & Developer</small><span><span>🇧🇷</span><ArrowRight size={13} /><span>🇦🇷</span></span></div></div><div className="founder-story"><p className="section-label">{t.founder[0]}</p><h2>{t.founder[1]}</h2><p>{t.founder[2]}</p><p>{t.founder[3]}</p><blockquote>{t.founder[4]}</blockquote></div></section>
    <section className="trust band" id="confianza"><div className="trust-symbol"><img src={brandMark} alt="" /></div><div className="trust-copy"><p className="section-label">{t.trust[0]}</p><h2>{t.trust[1]}</h2><p>{t.trust[2]}</p></div><div className="trust-points"><div><ShieldCheck /><span><strong>{t.trust[3]}</strong>{t.trust[4]}</span></div><div><HeartHandshake /><span><strong>{t.trust[5]}</strong>{t.trust[6]}</span></div></div></section>
    <section className="signup" id="acceso"><div className="signup-inner"><p className="section-label">{t.signup[0]}</p><h2>{t.signup[1]}</h2><p>{t.signup[2]}</p>{sent ? <div className="success-message" role="status"><Check size={20} />{t.signup[6]}</div> : <form onSubmit={submit}><label className="sr-only" htmlFor="email">{t.signup[3]}</label><input id="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder={t.signup[4]} required /><button className="button button-primary" type="submit">{t.signup[5]}<ArrowRight size={18} /></button></form>}<small>{t.signup[7]}</small></div></section>
  </main><footer><Logo /><p>{t.footer}</p><span>© {new Date().getFullYear()} Mudavi</span></footer></div>;
}
