arb-dir: lib/app/localization/arb
template-arb-file: app_en.arb
output-dir: lib/app/localization/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
